apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: storefront-api
  template:
    metadata:
      labels:
        app: storefront-api
    spec:
      containers:
        - name: storefront-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: DATABASE_URL
            value: "sqlite:////data/storefront.db"
